@startuml

[*] --> Backlog

Backlog: User created Issues
Backlog --> ToPrioritize: Relevant
Backlog --> Blocked
Backlog --> [*]: Irrelevant

ToPrioritize: Issue deemed relevant by PO

ToPrioritize --> ToDo: Milestone creation
ToPrioritize --> Blocked

ToDo: Issue prioritized
ToDo: Issue assigned
ToDo: Issue associated with milestone
ToDo --> InProgress: Branch creation
ToDo --> Blocked

InProgress --> ToQualify: Released in qualification environment
InProgress --> Blocked

ToQualify: Ongoing qualification
ToQualify --> Done: OK
ToQualify --> ToDo: KO - Rollback in qualification environment
ToQualify --> Blocked

Done: Issue resolution qualified
Done --> Closed: Released in prod/sandbox environments

Closed --> [*]

Blocked: Reasons for an issue to be blocked:
Blocked: - waiting another issue to be resolved
Blocked: - waiting solution from the source project
Blocked: - lack of documentation
Blocked: - requires a know-how currently unavailable
Blocked: - ready but not for the current milestone
Blocked: ...




'note left of Backlog: test

@enduml