@startuml

start
    floating note
        Sprint lasts 4 weeks
        Version incrementation depends on
        epics/user-stories content.
    end note

group Milestone preparation
    floating note
        Prepared by the PO
        from the backlog
    end note
    :Epics/user-stories assessment;
    split
        :Selected user-stories task division;
    split again
        :Selected user-stories priorisation;
    split again
        :Selected user-stories assignation;
    split again
        :Selected user-stories load estimation;
    end split
end group

group Milestone creation
    floating note
        Meating with the whole team
    end note
    :Adjust the milestone preparation;
end group

group Issues resolution
    floating note
        Daily meeting
    end note
    fork
        repeat
            :User-story 1 resolution;
            :User-story 1 qualification;
        repeat while (Qualification OK?) is (no) not (yes)
    fork again
        repeat
            :User-story 2 resolution;
            :User-story 2 qualification;
        repeat while (Qualification OK?) is (no) not (yes)
    fork again
        repeat
            :User-story ... resolution;
            :User-story ... qualification;
        repeat while (Qualification OK?) is (no) not (yes)
    end fork
    :Test d'intégration;
end group


group Release
    note
        Update the "about" section with
        the new version and the
        change_log.html page.
    end note
    :Sprint validation and feedback meeting;
    :Prod/sandbox release;
end group

stop



@enduml