id: aphp.fhir.fr.formbuilder
canonical: https://aphp.fr/ig/fhir/formbuilder
name: APHPFormBuilder
title: Guide d'implémentation de l'AP-HP FormBuilder
description: Le guide d'implémentation de l'Assistance Publique - Hôpitaux de Paris FormBuilder
status: active # draft | active | retired | unknown
version: 1.14.0
jurisdiction: urn:iso:std:iso:3166#FR "France" # https://www.hl7.org/fhir/valueset-jurisdiction.html
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: AP-HP
  url: https://aphp.fr

dependencies:
  hl7.fhir.fr.core: 2.1.0

pages:
  index.md:
    title: IG Home
  fb-quickstart.md:
    title: Quickstart
  change_log.md:
    title: Change log

menu:
  IG Home: index.html
  FormBuilder:
    Quickstart: fb-quickstart.html
  More:
    Change log: change_log.html